/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://goonrydmxfh35bgoqpuuie3ugu.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-o3jximjtojfk7cqjktn52cp7oi",
    "aws_cloud_logic_custom": [
        {
            "name": "testApi",
            "endpoint": "https://b8clsiiqub.execute-api.eu-central-1.amazonaws.com/staging",
            "region": "eu-central-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-central-1:cab94ab5-c4b1-49da-aaca-2c445ba74fcd",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_uAhZfflfq",
    "aws_user_pools_web_client_id": "3obb5rle883jqg3fsg4254it2r",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "BIRTHDATE",
        "EMAIL",
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "bibip-app-storage-8f58d563204655-staging",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
